### ISSUE TITLE
Catalina Downloads Mojave

### ISSUE THREAD

**Issue by mheeniac** [SpaceinvaderOne/Macinabox#1]
Left the docker container at default settings and install flavour --catalina. The file tree/names all say Catalina as expected but once getting to the installation I am prompted with macOS Mojave installation. 

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Starting process at Tue Oct 29 21:08:45 Europe 2019
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

I am going to download the Catalina recovery media. Please be patient!
.
.
Collecting requests (from -r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
Collecting click (from -r requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->-r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl (125kB)
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl (154kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 1))
Installing collected packages: urllib3, certifi, chardet, requests, click
Successfully installed certifi-2019.9.11 chardet-3.0.4 click-7.0 requests-2.22.0 urllib3-1.25.6
2019-10-29 21:08:47,592 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
2019-10-29 21:08:49,288 Selected macOS Product: 061-26589
Full install starting to unraid domain /image/MacinaboxCatalina
.
.
mkdir: created directory '/image/MacinaboxCatalina'
I have created the Macinabox directories
.
.
Formatting '//image/MacinaboxCatalina/macos_disk.img', fmt=raw size=68719476736
.
Created vdisk as type raw
.
.

dmg2img v1.6.7 (c) vu1tur (to@vu1tur.eu.org)

/Macinabox/tools/FetchMacOS/BaseSystem/BaseSystem.dmg --> /image/MacinaboxCatalina/Catalina-install.img

**Comment by lhaus** [comment]
I have exactly the same issue. completely fresh unraid install, 5.8 rc4

**Comment by lhaus** [comment]
found the issue - @SpaceinvaderOne you are using the -l flag for fetch.sh in fetchmacos, which isn't reliably catalina. 10.15.1 id is 041-83630, it downloads the correct dmg with `tools/FetchMacOS/fetch.sh -p 041-83630  -c PublicRelease`

**Comment by SpaceinvaderOne** [comment]
Yes thanks lhaus. The id numbers seem to change too I have found. I will need to keep checking this in future. 
I have just pushed the change and so its now id using id 041-83630 for 10.15.1

**Comment by lhaus** [comment]
@SpaceinvaderOne i tried manually overwriting basessytem.dmg before you pushed the fix, that installed catalina 10.15.1 but couldn't boot with "cannot load kernel cache" / forbidden icon. i'll retry now within the script but I don't think it will work. any ideas?

**Comment by mheeniac** [comment]
Just want to confirm that it worked flawlessly after updating the container. The VM installing Catalina as we speak. Thanks for the great release and quick fix @SpaceinvaderOne !
