### ISSUE TITLE
Hide VM From MacOS

### ISSUE THREAD

**Issue by mitchross** [SpaceinvaderOne/Macinabox#11]
can you incorporate this change? https://github.com/kholia/OSX-KVM/commit/453485ee750e2ccb727fc0d5aa84c7858eb55fc8

I need this so I can set up content caching https://support.apple.com/guide/mac-help/set-up-content-caching-on-mac-mchl3b6c3720/mac

error: https://www.reddit.com/r/macsysadmin/comments/9zd5ca/cache_server_in_a_vm/

**Comment by ofawx** [comment]
You can make that change in the Unraid VM XML manually. It doesn't play nice with macOS though; it does let you enable content caching but it will consume all available CPU from the host's perspective.

**Comment by ofawx** [comment]
[I've written a kernel patch for Clover/OpenCore that resolves this issue without the CPU overhead.](https://github.com/ofawx/VmAssetCacheEnable)

**Comment by mitchross** [comment]
thanks @ofawx do you have instructions for this as it relates to the Unraid setup?

**Comment by ofawx** [comment]
I'll update the instructions in my repo as it pertains to Macinabox and let you know 👍

**Comment by ofawx** [comment]
@mitchross good to go, probably will take you about an hour. Feel free to raise an issue on my repo if you have any trouble, otherwise a ⭐️ to let me know it helped you would be appreciated 😄

**Comment by mitchross** [comment]
@ofawx This worked! Took 20 mins.
