### ISSUE TITLE
Please update the product id for Catalina update released today

### ISSUE THREAD

**Issue by asterisx** [SpaceinvaderOne/Macinabox#12]
A new version 10.15.4 was released today and the older version is broken.

**Comment by tarz4n** [comment]
Came here to ask the same

**Comment by SpaceinvaderOne** [comment]
All done :)

**Comment by tarz4n** [comment]
Great! Just tried - getting a "Product ID 061-44387 could not be found." :(

**Comment by tarz4n** [comment]
I can see it was updated again, and now it works. Thanx!

**Comment by bmwbry** [comment]
I'm currently trying to complete a fresh install of macOS Catalina and I'm receiving the error "Product ID 041-40615 could not be found."

This seems like the proper place to put this issue, please update the container for the most recent macOS catalina product ID.

**Comment by SpaceinvaderOne** [comment]
updated now to  061-96006

**Comment by Irrelon** [comment]
How do we make these changes ourselves? 061-06006 is not working now.

Where do you get the new id and how do you set it?

**Comment by jlmbkd** [comment]
It looks like the version has been updated to 001-08763.   Is there a way to update this ourselves to relieve some of this burden from you?   Appreciate all the help!
