### ISSUE TITLE
Nvidia GPU ?

### ISSUE THREAD

**Issue by burton666** [SpaceinvaderOne/Macinabox#13]
After looking at your youtube-video about using one gpu and switching between VMs it looked like you started MacOS Catalina using a nvidia 1080. Is that possible now? Do you have any instructions of how to do this?

**Comment by TheBlueKingLP** [comment]
It was always possible, just no hardware acceleration and painfully slow, not door of that was the case in that video though.

**Comment by SpaceinvaderOne** [comment]
Still no Nvidia drivers available for Mojave/ Catalina :(
