### ISSUE TITLE
Clover issue

### ISSUE THREAD

**Issue by Young-3** [SpaceinvaderOne/Macinabox#2]
I have watched your youtube video, but I still have many questions, thank you
1、Mount clover.qcow2 EFI, cp clover.qcow2 EFI to OSX EFI, remove clover.qcow2 and install image. Then reboot, can't boot，black screen
2、Changing the product model results in boot failure and black screen, imac 14 to imac 18、19
3、The launch logo is in the upper left, blurred screen
4、Can I customize the clover.qcow2 file?

**Comment by SpaceinvaderOne** [comment]
To customize clover please use clover configurator.
