### ISSUE TITLE
Product ID Error

### ISSUE THREAD

**Issue by kskoba** [SpaceinvaderOne/Macinabox#20]
Apple updated product IDs recently.
Installation attempt returns the following:

```
I am going to download the Catalina recovery media. Please be patient!
.
.
Collecting requests (from -r requirements.txt (line 1))
Downloading 
[truncated]
Successfully installed certifi-2020.4.5.1 chardet-3.0.4 click-7.1.2 requests-2.23.0 urllib3-1.25.9
2020-05-27 16:24:25,452 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Product ID 061-96006 could not be found.
```

**Comment by tygbenn** [comment]
I am having the same issue.

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Starting process at Wed May 27 19:07:07 America 2020
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

I am going to download the Catalina recovery media. Please be patient!
.
.
Collecting requests (from -r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58kB)
Collecting click (from -r requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->-r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl (126kB)
Collecting chardet<4,>=3.0.2 (from requests->-r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl (157kB)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 1))
Installing collected packages: urllib3, chardet, certifi, requests, click
Successfully installed certifi-2020.4.5.1 chardet-3.0.4 click-7.1.2 requests-2.23.0 urllib3-1.25.9
2020-05-27 19:07:11,202 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Product ID 061-96006 could not be found.

**Comment by jbagdon** [comment]
I have a similar issue but with a different product ID:
"Product ID 061-70033 could not be found."
