### ISSUE TITLE
Product ID 061-70033 could not be found.

### ISSUE THREAD

**Issue by nickceriello** [SpaceinvaderOne/Macinabox#21]
Apple appears to have changed things again. Perhaps it would be helpful to add some information on how users can obtain an updated code even if just in the script's comments.

**Comment by mercuryin** [comment]
Same problem here, id incorrect. Any idea how to bypass this ? Thanks

**Comment by mytab0r** [comment]
+++

**Comment by mytab0r** [comment]
mb try Update Product ID: 001-04366 ?

**Comment by yoyoma** [comment]
Click Docker Select "Console".
`$ "Macinabox/tools/FetchMacOS/fetch.sh" -l -c PublicRelease
2019-12-11 21:59:42,362 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
2020-06-03 22:46:39,132 Selected macOS Product: 001-04366
Fetching BaseSystem/BaseSystem.dmg ...  [####################################]  100% `

**Comment by jdaniels002** [comment]
@Superflix26 not sure if you ever got it working only copy whats after the '$' and it should start to go

**Comment by mytab0r** [comment]
ok. but what next?

**Comment by jdaniels002** [comment]
nope spoke too soon

**Comment by mytab0r** [comment]
> nope spoke too soon

oh, sorry

**Comment by jdaniels002** [comment]
> ok. but what next?

@mytab0r Ok got tired of waiting for the fixed to be merged or for this to be written here. I ended up editing the fetch.sh file in the docker container using vim and then restarted the container to make sure all scripts ran properly. here's a guide that most people should be able to fallow

Step by step
1. Change the Console from shell to bash - IMO Shell sucks but both work so whatever. click > edit change Console shell command: Shell to bash. Click Apply it should immediately restart 

2. Start the Console - click the icon to bring up the menu then click console 

3. install Vim or some other Console editor - install vim using the command `# apt-get install vim` Press y then enter to continue

4. open the fetch script - type `# vim Macinabox/unraid.sh ` to open in vim or your chosen editor

5. Change Update ID for Catalina to 001-04366 as **jonasmaturana** mentioned the current ID for Catlina is 001-04366 scroll down to about line 167 and change the ID 061-70033 to the new one. **note for users who have never used vim** press 'i' to enter --insert-- mode then edit as normal. when your done editing press escape 'Shift+;' type wq then enter to save and exit vim

6. restart the container - you could probably just run the script but i don't know what else runs in the before or after the get script.

7. continue following the video

**Comment by tzabbi** [comment]
It works! Thanks. But how I can find the Product ID if Apple change it again?
