### ISSUE TITLE
How can I change the Resolution?

### ISSUE THREAD

**Issue by Shimakuchi** [SpaceinvaderOne/Macinabox#24]
On Windows VMs the RDP Client can handle or adopt the Resolution. Is there a way to achieve this with a mac VM?

**Comment by jacklocke** [comment]
try occ, for me works!
in EFI: config.plist in output section

**Comment by jeff15110168** [comment]
> 

what are you meant to do when you mount your EFI partition / open config.plist in a text editor like BBEdit? Mine just says the below. What do i need to do so I can switch resolutions dynamically within the system settings (i.e. from 1920x1080 to 2048x1536 etc.)

```
		<key>Output</key>
		<dict>
			<key>ClearScreenOnModeSwitch</key>
			<false/>
			<key>ConsoleMode</key>
			<string></string>
			<key>DirectGopRendering</key>
			<false/>
			<key>ForceResolution</key>
			<false/>
			<key>IgnoreTextInGraphics</key>
			<false/>
			<key>ProvideConsoleGop</key>
			<true/>
			<key>ReconnectOnResChange</key>
			<false/>
			<key>ReplaceTabWithSpace</key>
			<false/>
			<key>Resolution</key>
			<string>Max</string>
			<key>SanitiseClearScreen</key>
			<false/>
			<key>TextRenderer</key>
			<string>BuiltinGraphics</string>
			<key>UgaPassThrough</key>
			<false/>
		</dict>
```

**Comment by RezzZ** [comment]
> try occ, for me works! in EFI: config.plist in output section

any chance you can point me into the dirrection how to do this?

**Comment by jaybeedk** [comment]
I'm sure that there is a proper way to change the resolution, but here is the brute-force method that worked for me, running Seqoia on the version of Macinabox with Last Update: Nov 6, 2024 running the commands below in a Unraid 7.2.3 webterminal browser window.

**Attach image:**
_mkdir -p /mnt/tmp
losetup -Pf --show /mnt/user/domains/Sequoia/Sequoia-opencore.img_

**Change XXX to reflect the output from losetup, e.g. /dev/loop4 becomes /dev/loop4p1**
_mount /dev/loop**XXX**p1 /mnt/tmp_

**Find the line (e.g. 1771) where the dictionary starts (as CTRL+W to search closed my webterminal browser window)**
_grep -n "<key>Output</key>" /mnt/tmp/EFI/OC/config.plist
nano **+1771** /mnt/tmp/EFI/OC/config.plist_

Scroll down to "<key>Resolution</key>" and change it's string value to "3840x2160@32" for 4K, "2560x1440@32" for 1440p
Press CTRL+X to exist, answer "Y" to save and press enter to overwrite

**Cleanup:**
_umount /mnt/tmp
losetup -D_
