### ISSUE TITLE
Product ID 061-94403 could not be found.

### ISSUE THREAD

**Issue by koldogut** [SpaceinvaderOne/Macinabox#27]
While installing Catalina (Full Install) the log stops here:

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Starting process at Sun Sep 27 11:41:43 Europe 2020
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

I am going to download the Catalina recovery media. Please be patient!
.
.
Collecting requests (from -r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl (61kB)
Collecting click (from -r requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->-r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl (127kB)
Collecting chardet<4,>=3.0.2 (from requests->-r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl (156kB)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 1))
Installing collected packages: urllib3, chardet, certifi, requests, click
Successfully installed certifi-2020.6.20 chardet-3.0.4 click-7.1.2 requests-2.24.0 urllib3-1.25.10
2020-09-27 11:42:19,899 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Product ID 061-94403 could not be found.

**Comment by frostybrew** [comment]
Can confirm, I am seeing the same issue installing Catalina. It appears as though Mojave and High Sierra are unaffected.
