### ISSUE TITLE
Helper scripts don't use paths defined in docker container.

### ISSUE THREAD

**Issue by vrelk** [SpaceinvaderOne/Macinabox#32]
I noticed that you don't have the paths for appdata defined in the VM helper scripts (either automatically using those from the docker container, or at the top of the file). I have 2 appdata folders, one that is cache only, and another one that uses the array and is covered by the parity drives. In this situation, the helper scripts don't work as the files it is trying to access aren't in the normal appdata folder, which it is set to look in.

Just a thought that you might either template them, move the path to a variable at the top, or at least mention that it may need to be changed.

**Comment by SpaceinvaderOne** [comment]
Sorry for this you would have to edit the script manually
