### ISSUE TITLE
Big Sur: Intel network appears as VMXNet3 under macOS

### ISSUE THREAD

**Issue by TheManchineel** [SpaceinvaderOne/Macinabox#36]
I've installed macOS Big Sur following the procedure to the letter and have already repeated the process twice. The config file appears correct from Unraid and running the helper script. This is my only macOS VM by the way:

![image](https://user-images.githubusercontent.com/37479927/106317249-552eff00-626e-11eb-9ad4-96c7ade698f2.png)
![image](https://user-images.githubusercontent.com/37479927/106317071-07b29200-626e-11eb-806f-f087fbe89151.png)
And yet, this is what I get in System Preferences:
![image](https://user-images.githubusercontent.com/37479927/106317347-80195300-626e-11eb-8396-4898c9c6bd94.png)

And like in #30, whenever I try to set up Apple services I get the same error:
![image](https://user-images.githubusercontent.com/37479927/106316973-e356b580-626d-11eb-91e5-3d684760df1f.png)

No other network interface is set up and neither does any other appear in Network Preferences. Obviously I have already tried restarting the VM multiple times. Has anyone gotten Apple Services to work with Macinabox? If so, what does your Network System Preferences look like?

**Comment by nicx** [comment]
+1
