### ISSUE TITLE
Unable to install certain software as harddrive is read-only

### ISSUE THREAD

**Issue by EricDiepeveen** [SpaceinvaderOne/Macinabox#4]
Steps to reproduce

1) Download the unity installer (https://unity3d.com/get-unity/download?thank-you=update&download_nid=63169&os=Mac)
2) Continue through the installer flow.
3) Notice that you cannot select the main hard drive to install the application.

The main hard drive in Mac OS is read only for the admin user. If you look at the info of the volume it says it's read-only for the admin user.

**Comment by SpaceinvaderOne** [comment]
This is a macOS issue and not related to this container. :)
