### ISSUE TITLE
Big Sur Product ID could not be found

### ISSUE THREAD

**Issue by bmwbry** [SpaceinvaderOne/Macinabox#40]
Tried to install Big Sur using method 1 and it would install Catalina. Removed all data and templates and tried method 2 install, installation wouldn't complete after waiting for about 45 minutes.

I then went through the appdata folder for macinabox and found "macinabox_Big Sur.log", this log said the following:

I am going to download the BigSur recovery media. Please be patient!
.
.
Product ID 001-86606 could not be found.

**Comment by discojon** [comment]
I also attempted to install Big Sur but ended up with Catalina.

**Comment by organom** [comment]
same on this side, catalina recovery is the one conning up when selecting big sur

**Comment by gloubix** [comment]
Same for me selected catalina method1 or 2 no Big Sur.
Has anyone tried to upgrade from Catalina ? Is it possible ?

**Comment by bmwbry** [comment]
> Same for me selected catalina method1 or 2 no Big Sur.
> Has anyone tried to upgrade from Catalina ? Is it possible ?
> 
> Someone can share his Big Sur imgs to have a temporary solution ?


I did upgrade to Big Sur using macOS update, but it was tricky and would boot back to recovery screen. My graphics card was passed through and wouldn’t give me any output so I had to delete the maxinabox template and recreate it to use VNC again to get back in. It also had trouble recognizing my Logitech mouse and keyboard even though I had the usb controller the dongle was connected to passed through..

Had to do this a few times until it was done with multiple reboots through the update process. I then recreated my VM template using macinabox and was able to pass through my rx480 again.

It seems to be working okay now though! I do still have to select the disk upon startup though...

**Comment by bpelech** [comment]
https://github.com/SpaceinvaderOne/Macinabox/issues/33#issuecomment-808819247

**Comment by SpaceinvaderOne** [comment]
> [#33 (comment)](https://github.com/SpaceinvaderOne/Macinabox/issues/33#issuecomment-808819247)
> 
> For everyone who ended up with Catalina instead of Big Sur, here's what I was able to gather and do to fix this issue:
> 
> 1. Use method 2 as explained in the video from SpaceInvader (because this method expects downloading "InstallAssistant.pkg" which needs to be extracted).
> 2. Start Macinabox
> 3. Open console - click on Macinabox docker icon and then Console.
> 4. Install nano (or vim) - `apk add nano`
> 5. Edit unraid.sh - `nano /Macinabox/unraid.sh`. Find and replace `001-86606` to `071-05432` (this is correct big sur ID)
> 6. Restart Macinabox
> 7. Follow the SpaceInvader video
> 
> Additional troubleshooting:
> 
> * If you were too slow and wrong image was already downloaded while you were editing the unraid.sh no worries. Just delete the files ("BigSur-install.img" and "BigSur-opencore.img") from isos folder and restart Macinabox. It will download the correct files again.
> * If you messed up somehow with the VM: delete the VM, restart the Macinabox and run the "1_macinabox_helper" user script again.
> * If you can't delete the VM (I saw this error once "Requested operation is not valid: cannot delete inactive domain with nvram"), run this command from shell `virsh undefine --nvram "Macinabox BigSur"`. You can open the shell with the >_ icon from the right top corner.
> 
> Hope SpaceInvader will be able to find the time to fix the Macinabox. Until then - stay with catalina or try this fix.
> 
> If SpaceInvader will read this post: HUGE THANK YOU for this tool and all your work. You rock man! :-)

Thanks bpelech glad you like Macinabox. And thanks very much for posting the id fix.
Sorry I havent had much time to look at Macinabox recently due to work. But i had a look at Macinabox today and pushed a new build to dockerhub. Macinabox   is now fixed Big Sur for  both download  method 1 and method 2 (method 2 using your product id ) Method 1 is faster to download  as it downloads a baseimage of 625 megs and makes the install image from that. Method 2 uses the InstallAssistant.pkg which is much larger.

**Comment by SpaceinvaderOne** [comment]
Big sur now downloading correctly
