### ISSUE TITLE
Stuck at Apple Logo

### ISSUE THREAD

**Issue by axiades** [SpaceinvaderOne/Macinabox#46]
Hello,

i have a Problem with MacInABox.

the VM is Stuck at the Apple Logo after starting the MacOS Base System

but the vm is doing nothing anymore.

**Comment by plexecutor** [comment]
@axiades how many cores are you passing to the VM? You should do a 'normal' amount such as 2, 4, or 8 and avoid odd numbers or 6/12. If you insist on passing an odd number or more than 8 cores, make sure you edit the macinabox helper script and tell it to remove topology up near the top of the script.

**Comment by peerstelter** [comment]
I Have the same Problem... i Recorded it... i followed the youtube guide exactly an leave everything default. same issus with Big Sur / Catalina / Mojave... anyboddy an idea ?
https://youtu.be/1n4nvovMgbQ

**Comment by 82ghost82** [comment]
Please read this:
https://github.com/SpaceinvaderOne/Macinabox/pull/47#issuecomment-870724002
