### ISSUE TITLE
Passthrough a GPU 6900xt not work

### ISSUE THREAD

**Issue by ichswarox** [SpaceinvaderOne/Macinabox#56]
With the same setup, I successful passthrough a RX480 4G GPU to mac os running on Unraid, then I try 6900xt, not work? What I've tried.

1.Download 6900xt bios from techpowerup, apply in configuration, not work.
2.Reset xml then boot with RX480, it works, reset xml then boot with 6900xt, not work.
3.add agdpmod=pikera boot arg, not work, and the issue happened before apple logo appear.

**Comment by RodriMora** [comment]
I don't think there is support for the 6900xt on any version of Mac OS

**Comment by regs1980** [comment]
> 
> 
> I don't think there is support for the 6900xt on any version of Mac OS

https://support.apple.com/en-us/HT208544

**Comment by ichswarox** [comment]
> I don't think there is support for the 6900xt on any version of Mac OS

Get it work on my big sur hackintosh, working promising and I use it for rendering.

**Comment by ichswarox** [comment]
> 

I see, I will give proxmox a try
