### ISSUE TITLE
"Product ID 041-83630 could not be found."

### ISSUE THREAD

**Issue by mrgnw** [SpaceinvaderOne/Macinabox#6]
Hi! This looks absolutely amazing but I've run into this issue when I try to do Catalina full install: 
`Product ID 041-83630 could not be found.`

I see that this product ID was specified in commit fa9f2e8 in order to fix issue #1 "Catalina downloads Mojave"

Running fetch.sh with `-l` downloads Catalina now, not Mojave. Maybe we could fallback to `-l` if specifying the product id fails? (or vice versa)

### Troubleshooting

I'm brand new to unraid so I'm unsure how to tweak the install or troubleshoot there, but this is what I get when I clone the repo and run fetch.sh in macOS.

with `-p 041-83630`: Product ID 041-83630 could not be found
```
$ "Macinabox/tools/FetchMacOS/fetch.sh" -p 041-83630 -c PublicRelease
2019-12-11 21:59:40,165 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Product ID 041-83630 could not be found.
```

with `-l`: downloads Catalina, product: `061-10700`
```
$ "Macinabox/tools/FetchMacOS/fetch.sh" -l -c PublicRelease
2019-12-11 21:59:42,362 Network Request: Fetching https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
2019-12-11 21:59:43,837 Selected macOS Product: 061-10700
Fetching BaseSystem/BaseSystem.dmg ...  [####################################]  100% 
```

**Comment by DeanSellas** [comment]
I had this issue last night as well. I fixed it with this form post. https://forums.unraid.net/topic/84601-support-spaceinvaderone-macinabox/page/14/

**Comment by SpaceinvaderOne** [comment]
product id updated. Thanks for letting me know :)
