### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by BlueManRising** [SpaceinvaderOne/Macinabox#65]
I pulled the most recent pull requests, and forked a branch, unfortunately in Unraid when i change the repository to my own, it says that it : Unable to find image 'bluemanrising/macinabox:latest' locally 

im assuming due to the pull request coming up with 0 bytes its not grabing my repo, since im new to unraid, is there a way to manually download and put on my unraid server, and if so, where does it save, so when it fails to pull, I can just grab what I uploaded manually?

sorry if this has ever been asked before, just trying to get a working copy and like everyone else im having the same issue with the wrong version of os being downloaded, and then again, during the last steps of updating the esi, it hanging in boot like a previous issue states.

**Comment by BlueManRising** [comment]
actually i figured it out, needed a "Pro" version of Docker in order to link the hub to here.  That being said, if your looking for the most up todate (and yes you can see i just made all the changes associated to the last 5 pull requests) i have bluemanrising/macinabox running currently.  so in unraid, just change the repo to that and your getting the most up to date.  If you see it gone, then im sorry, i dont know how long i will keep it running.

**Comment by TheHackGuy** [comment]
Look on my profile. I got a github build script that uploads it to docker hub.

@SpaceinvaderOne said he's working on a new version of macinabox. So I suggest to wait instead of trying to fix things by yourself

**Comment by BlueManRising** [comment]
Ah thanks, well I'm just gonna fart around with it, I've broken it now 2 times, so onto build try no. 3 worst case I'll pull it down so no one does what I just did
