### ISSUE TITLE
macinabox stuck in the process of installing monterey.

### ISSUE THREAD

**Issue by Bradley-Liu** [SpaceinvaderOne/Macinabox#67]
with the logs i saw the following outputs and it stuck there. I've also noticed that no user-scripts are created when i check user-script plugin. 
Before installing the docker, I deleted the old appdata and docker template.  
Nothing makes any differences.
Any idears?

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

**Comment by Core-i99** [comment]
Provide logs of the docker container.

**Comment by Bradley-Liu** [comment]
Here is the full log of macinabox

**Comment by Core-i99** [comment]
This log is from an older version of macinabox. Clear all the macinabox related files and update it.

**Comment by Bradley-Liu** [comment]
Before update, I've already deleted the old appdata and docker template and the old docker image.
I did a fresh new installl of the docker. 
What else should I do to fully delete the docker and its related files?

**Comment by Core-i99** [comment]
The log is defenetively from an older version of Macinabox which still had virt manager. Try to remove data from appdata, the docker image, the domains folder and remove the docker template. That should be all needed to be cleared.
