### ISSUE TITLE
No Bootable Mac OS After Fresh Install

### ISSUE THREAD

**Issue by mitchross** [SpaceinvaderOne/Macinabox#69]
I followed all steps for Mac in a Box Install. Im using Big Sur. After installing Mac OS, I never see my "bigsur" drive.

![image](https://user-images.githubusercontent.com/6330506/156847714-5749780d-0204-4bdc-8daf-245ddfc29571.png)

**Comment by Core-i99** [comment]
Completely normal. The macos drive will first be called macos installer. Later In the installing process it will get the name you chose.
