### ISSUE TITLE
Black screen in some apps

### ISSUE THREAD

**Issue by bluegizmo83** [SpaceinvaderOne/Macinabox#71]
I've got a weird issue with Macinabox. I installed BigSur and its mostly working great, but in some apps, like Apple Maps, all I get is a black screen. Specifically with Maps, the app is visible, but the actual map section is just black.

![maps](https://user-images.githubusercontent.com/1000998/171557436-4ba3e7b2-3b6d-4b6d-8d4a-efc664e4d38c.jpg)

I've tried everything I can think of and I just can't get maps to show the actual maps.

**Comment by Core-i99** [comment]
You do have a metal capable gpu passed trough or not?

**Comment by bluegizmo83** [comment]
> You do have a metal capable gpu passed trough or not?

No, just using VNC, no passthrough.

**Comment by Core-i99** [comment]
That's normal then. I'm pretty sure apple maps uses metal, no gpu acceleration and you'll get this. Not an issue with macinabox.
