### ISSUE TITLE
[monterey]an error occurred while preparing the installation.try running this application again

### ISSUE THREAD

**Issue by warmJN** [SpaceinvaderOne/Macinabox#72]
Alert this error when installing monterey about 30 minutes,
i'm finded one problem, system date reduced by 8 hours,
so i'm used `date` command to fix it,However, this error is still displayed when reinstalling，
now,i'm go to terminal and input `date` command, the system date reduced by 8 hours.
i'm try to modify clock parameter in vm xml:
like this:
`<clock offset='localtime'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
    <timer name='tsc' present='yes' mode='native'/>
  </clock>`
this parameter operative in custom vm, not in the Macinabox generate vm.

**Comment by liwei9401** [comment]
i have the same question,
and i try to modify time but it doesn't work.

**Comment by warmJN** [comment]
> i have the same question, and i try to modify time but it doesn't work.

Error by version,
if you change machine type to q35-6.2,
you can change the system date,but still unable to install.
you can try to install big sur version, because I've already installed it.

**Comment by liwei9401** [comment]
> > i have the same question, and i try to modify time but it doesn't work.
> 
> Error by version, if you change machine type to q35-6.2, you can change the system date,but still unable to install. you can try to install big sur version, because I've already installed it.

ok，thx

**Comment by BillyLavoie** [comment]
I think it's an error with the install image created. Nothing I did would fix it. I spent two days trying. After a while I used the SAME VM but overwrote the Monterey_Install.img with one I created myself in MacOS and now it's installing fine.
