### ISSUE TITLE
Monterey Image downloaded and then download again during installation?

### ISSUE THREAD

**Issue by damarges** [SpaceinvaderOne/Macinabox#75]
I ran macinabox in unraid. It downloaded and createt a 3GB file called "Monterey-install.img"
I thought that means it would use this file during installation. But when I now start the monterey installation it downloads several gigabytes of data again... is that correct?

**Comment by Core-i99** [comment]
Yes this is correct. The 3gb is just the online installer. An offline installer would be 12+ gb.
