### ISSUE TITLE
Can't install Monterey

### ISSUE THREAD

**Issue by shigatena666** [SpaceinvaderOne/Macinabox#76]
Hi,

Been trying for the whole day to install MacOS Monterey using Macinabox.
I can successfully boot onto the VM created by the docker, but I get an error message saying.

Just to be more precise, I haven't touched the XML configuration created by the user scripts at all. I just tried running into VNC the VM and it ended up all there.
![image](https://user-images.githubusercontent.com/50152760/200189507-e51c3f88-fa47-442d-a6f1-df7cc3dc171f.png)

I have tried many other ways including making my personal USB installer (for both Ventura and Monterey) but didn't manage to make it work either.

If any of you has a clue I'd be grateful.

**Comment by Allesanddro** [comment]
Same here

**Comment by hoelee** [comment]
same

**Comment by akarabach** [comment]
same for me

**Comment by TRusselo** [comment]
ahh so its just Monterey, ill try big sur then.

**Comment by EduardTheThird** [comment]
Having the same issue.

**Comment by shigatena666** [comment]
Won't be fixed

**Comment by JamesDAdams** [comment]
same

**Comment by JamesDAdams** [comment]
Same

**Comment by muliangde** [comment]
same

**Comment by aUniqueUser** [comment]
sameeeeeeeeeeee
