### ISSUE TITLE
Update with the lastest version?

### ISSUE THREAD

**Issue by alekslyse** [SpaceinvaderOne/Macinabox#81]
Is it possible to get this script updated to include ventura so its possible to use the latest version, or is the project dead?

**Comment by SpaceinvaderOne** [comment]
I am rewriting macinabox at present and i hope to have finished in about a fortnight (so long as work commitments dont get in the way)
It will have support for ventura then. Also there will be no nee for any userscripts on unraid as there was in the previous version of macinabox. There are a number of improvements planned.

**Comment by h3llfire83** [comment]
hope you get it soon done - and thanks for your time and efforts spaceinvaderone

**Comment by workwithprashant** [comment]
@SpaceinvaderOne  I understand that it's very difficult to develop something along with work commitments so I appreciate all your time and efforts. Any ETA on launching revamped Macinabox with Ventura?

**Comment by rrowlands** [comment]
I need this! How much do we need to pay? I donated $20 a few months ago.

**Comment by meechgalhuquot** [comment]
Any chance you can provide a timeline on this? I'd like to upgrade my macOS VM to a more recent release. I'm willing to test if you want other eyes on it before you release

**Comment by 10bn** [comment]
I'd also highly apprechiate seeing the latest OSX Versions in Macinabox. 

I found this well documented guide, it might be a good point to start from for some of us:
https://github.com/Pavo-IM/Hackinabox

And this one: https://gist.github.com/nonkronk/8c5035a05c3faa26cf55d7f15b34b202

**Comment by xCaptainChris** [comment]
I'm just curious as well. I can't imagine the amount of work that goes into something like this. I am only spinning up a VM or docker to run bluebubbles.

**Comment by meechgalhuquot** [comment]
That's exactly the purpose of my VM as well, which is why I would like a newer version of macOS so that BlueBubbles can show edited messages properly On May 9, 2024, at 11:28 PM, xCaptainChris ***@***.***> wrote:﻿
I'm just curious as well. I can't imagine the amount of work that goes into something like this. I am only spinning up a VM or docker to run bluebubbles.

**Comment by xcellentavi** [comment]
@meechgalhuquot, if you feel like rolling up your sleeves a little bit, there is a guide that someone else posted on reddit that might help get this working on newer versions: https://www.reddit.com/r/unRAID/comments/19bdmjh/unraid_vm_macos_sonoma_with_macinabox/

If @SpaceinvaderOne is still working on this container update, the direct link to the pastbin is here: https://pastebin.com/tf77sMJy

The instructions start with Monterey and upgrade to Ventura, so it might help those asking in https://github.com/SpaceinvaderOne/Macinabox/issues/76, but not sure if Sonoma ultimately would work.

I am still comfortable running Big Sur so I haven't attempted this procedure yet.

**Comment by tomyslo1** [comment]
It's been updated! :-)

**Comment by xCaptainChris** [comment]
> It's been updated! :-)

Dude! Can’t wait to give it a try! Thanks!
