### ISSUE TITLE
white desktop in Sonoma

### ISSUE THREAD

**Issue by RezzZ** [SpaceinvaderOne/Macinabox#86]
just tried upgrading Ventura to Sequoia, although it works, I end up with a white/blank desktop. The system does run and I can start apps as expected. 
I also installing a brand new Sonoma and also there it results in a white desktop and icons/emoticons disappearing when setting up an account during setup. Probably a graphical issue?
Ventura seems to work best right now...

**Comment by tomyslo1** [comment]
I think this happens if you don't have a GPU passed-through. The default wallpaper is a video if I'm not mistaken, and it just shows it as white. Try choosing a static image for your wallpaper.

**Comment by RezzZ** [comment]
ahh you are right, with static desktop the white is gone. Thanks @tomyslo1 
no I just need to get my clipboard working to copy paste things between my real desktop and the VM :)
