### ISSUE TITLE
PCIe Devices not being passed through to VM

### ISSUE THREAD

**Issue by Gabriel-H4** [SpaceinvaderOne/Macinabox#88]
## Issue
After successfully creating a macOS VM, I then tried to pass a PCIe device through to the VM. It is passed through, but does not show up in macOS. The driver is installed, but the device is not displayed in System Information.

## Info
- Unraid Host: Xserve3,1
- Device: ATTO FastFrame
- VM info: macOS Sonoma
    - Also tried Big Sur

## Troubleshooting Steps
- Change macOS VM version to Big Sur
- Update OpenCore config to MacPro7,1
- Tested PCIe device in Windows VM (works)
- Tried other PCIe devices (none are passed through)
    - Video Card (natively supported by macOS)
    - Optical Drive (SATA not PCIe)
 - Tested on bare metal macOS install (works)

**Comment by SpaceinvaderOne** [comment]
macinabox is only a tool to install macOS as a vm. It basically installs a virtual Hackintosh. So for hardware support it is just the same as a bare metal Hackintosh. For passthrough of GPU this will require you to do additional things inside of opencore after you have a basic install, such as  Lilu and WhateverGreen. Check out hackintosh guides here https://dortania.github.io/GPU-Buyers-Guide/
